### ISSUE TITLE
FAIL to run oneflow diffusion sample. AttributeError: module 'torch' has no attribute 'to_dlpack'

### ISSUE THREAD

**Issue by samuellees** [Oneflow-Inc/diffusers#120]
### Describe the bug

Hello,
   I follow the steps [here](https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#without-docker) to install oneflow and oneflow-diffusion. But got Error when runing the demo code.

The python code and logs as following:

### Reproduction

```
import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=torch.float16,
)

pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with torch.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")
```

### Logs

```shell
(3.8-oneflow) root@89d9cf1b247e:~/stable-diffusion# python3 demo.py
libibverbs not available, ibv_fork_init skipped
Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 30545.68it/s]
Traceback (most recent call last):
  File "/root/diffusers/src/diffusers/modeling_oneflow_utils.py", line 95, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 508, in load
    return load(path, global_src_rank, map_location, *extra_data)  # type: ignore
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 418, in load_from_pytorch_file
    flow_obj = ArgsTree(torch_obj).map_leaf(torch_tensor_to_flow)
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/args_tree.py", line 216, in map_leaf
    return self._execute_mapping(args_to_map, map_function)
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/args_tree.py", line 224, in _execute_mapping
    mapped_value = value.__class__(
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/args_tree.py", line 226, in <lambda>
    lambda x: (x[0], self._execute_mapping(x[1], map_function)),
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/args_tree.py", line 236, in _execute_mapping
    mapped_value = map_function(value)
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 414, in torch_tensor_to_flow
    return flow.utils.tensor.from_torch(x)
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/site-packages/oneflow/utils/tensor/from_or_to_torch_tensor.py", line 65, in from_torch
    return flow.from_dlpack(torch.to_dlpack(torch_tensor))
AttributeError: module 'torch' has no attribute 'to_dlpack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/diffusers/src/diffusers/modeling_oneflow_utils.py", line 99, in load_state_dict
    if f.read().startswith("version"):
  File "/workspace/miniconda/envs/3.8-oneflow/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
  File "/root/diffusers/src/diffusers/pipeline_oneflow_utils.py", line 769, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/root/diffusers/src/diffusers/modeling_oneflow_utils.py", line 473, in from_pretrained
    state_dict = load_state_dict(model_file)
  File "/root/diffusers/src/diffusers/modeling_oneflow_utils.py", line 111, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for '/root/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/*hidden*/vae/diffusion_pytorch_model.bin' at '/root/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/*hidden*/vae/diffusion_pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Segmentation fault (core dumped)
```

### System Info

linux 
cuda 11

**Comment by samuellees** [comment]
@Alokia  Help！[Thank u in advance ]

**Comment by jackalcooper** [comment]
please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion

**Comment by samuellees** [comment]
> please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion

It can NOT work. 

Where is the [new non-fork implementation]?  

Have you followed this [wiki](https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion) and try its demo code?

**Comment by jackalcooper** [comment]
> Where is the [new non-fork implementation]?

it is the main branch of this repo now.

> Have you followed this [wiki](https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion) and try its demo code?

yes, and it has been updated with info like

```
python3 -m pip install "transformers>=4.26" "diffusers[torch]==0.12.1"
python3 -m pip uninstall accelerate -y
python3 -m pip install onediff
python3 -m onediff.demo
```

you might need to reload the page or clean browser cache? sorry for the inconvenience

**Comment by Alokia** [comment]
@samuellees run successfully

```
import oneflow as torch
from onediff import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=torch.float16,
)

pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with torch.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")
```

```
~: python3 test.py 
Fetching 16 files: 100%|████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 64096.34it/s]
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate

.
/home/zhaodi/miniconda3/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
/home/zhaodi/oneflow/python/oneflow/nn/modules/module.py:152: UserWarning: Interpolate() is called in a nn.Graph, but not registered into a nn.Graph.
  warnings.warn(
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 18.23it/s]
```

**Comment by jackalcooper** [comment]
when running demo, the output should be like this
```
$ docker run --rm -it \
>   --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
>   -v ${HF_HOME}:${HF_HOME} \
>   -v ${PWD}:${PWD} \
>   -w ${PWD} \
>   -e HF_HOME=${HF_HOME} \
>   -e HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN} \
>   oneflowinc/onediff:cu117 \
>   python3 -m onediff.demo # --prompt "a photo of an astronaut riding a horse on mars"
Unable to find image 'oneflowinc/onediff:cu117' locally
cu117: Pulling from oneflowinc/onediff
Digest: sha256:0df6ea93ba80293e0a562a7ab4bcca363431aebeb8b22dc3eef19208176a6440
Status: Downloaded newer image for oneflowinc/onediff:cu117

=============
== PyTorch ==
=============

NVIDIA Release 22.09 (build 44877844)
PyTorch Version 1.13.0a0+d0d6b1f

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2022 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 3636.15it/s]
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate

.
W20230222 03:09:36.381129   232 cuda_stream.cpp:48] Runtime version 8.4 of cuDNN incompatible with compiletime version 8.5.
                                                                         
                                                                         
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:10<00:00,  4.97it/s]
```

**Comment by samuellees** [comment]
> you might need to reload the page or clean browser cache? 

Good idea, I have run successfully with torch + official diffusers.  But the same error occurs when I switch conda env from torch to oneflow.  Maybe there is somwthing error with the weight cache of hugging face ?

**Comment by jackalcooper** [comment]
> Good idea, I have run successfully with torch + official diffusers. But the same error occurs when I switch conda env from torch to oneflow. Maybe there is somwthing error with the weight cache of hugging face ?

the weight should be compatible with oneflow but you need to update your script with the latest examples in the wiki.

**Comment by samuellees** [comment]
> when running demo, the output should be like this
@jackalcooper  ok, thanks. let me try it with docker env.

**Comment by samuellees** [comment]
@jackalcooper @Alokia  Running successfully with docker. Thanks guys!
