### ISSUE TITLE
Why does oneflow still interfere with diffusers

### ISSUE THREAD

**Issue by chavinlo** [Oneflow-Inc/diffusers#131]
```python
Traceback (most recent call last):
  File "/root/node/threads/test_compiler.py", line 4, in <module>
    compile(
  File "/root/node/threads/compiler.py", line 119, in compile
    tmpUnet = UNet2DConditionModel.from_pretrained(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 608, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/root/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 210, in from_config
    model = cls(**init_dict)
  File "/root/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 569, in inner_init
    init(self, *args, **init_kwargs)
  File "/root/env/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 249, in __init__
    down_block = get_down_block(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 89, in get_down_block
    return CrossAttnDownBlock2D(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 771, in __init__
    Transformer2DModel(
  File "/root/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 569, in inner_init
    init(self, *args, **init_kwargs)
  File "/root/env/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 179, in __init__
    [
  File "/root/env/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 180, in <listcomp>
    BasicTransformerBlock(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/attention.py", line 223, in __init__
    self.attn1 = CrossAttention(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 105, in __init__
    processor = AttnProcessor2_0() if hasattr(F, "scaled_dot_product_attention") else CrossAttnProcessor()
  File "/root/env/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py", line 44, in __getattr__
    raise ModuleNotFoundError(self.module.__name__ + "." + name + error_msg)
ModuleNotFoundError: oneflow.nn.functional.scaled_dot_product_attention is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.
```

**Comment by jackalcooper** [comment]
this should be resolved by installing 0.12.1 of diffusers
```
python3 -m pip install "transformers>=4.26" "diffusers[torch]==0.12.1"
```

**Comment by chavinlo** [comment]
> this should be resolved by installing 0.12.1 of diffusers
> 
> ```
> python3 -m pip install "transformers>=4.26" "diffusers[torch]==0.12.1"
> ```

```python
Exception in thread Thread-1 (image_generator):
Traceback (most recent call last):
  File "/root/env/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 99, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/root/env/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/env/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/root/env/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
  File "/root/env/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py", line 44, in __getattr__
    raise ModuleNotFoundError(self.module.__name__ + "." + name + error_msg)
ModuleNotFoundError: oneflow._utils._rebuild_tensor_v2 is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/env/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 105, in load_state_dict
    if f.read().startswith("version"):
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/node/threads/base.py", line 50, in image_generator
    unet = compile(
  File "/root/node/threads/compiler.py", line 120, in compile
    tmpUnet = UNet2DConditionModel.from_pretrained(
  File "/root/env/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 542, in from_pretrained
    state_dict = load_state_dict(model_file)
  File "/root/env/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 117, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for '/root/.cache/huggingface/diffusers/models--Linaqruf--anything-v3.0/snapshots/1cfddae5cd94af6dbea2d4bb8dcaea8b7d215a1f/unet/diffusion_pytorch_model.bin' at '/root/.cache/huggingface/diffusers/models--Linaqruf--anything-v3.0/snapshots/1cfddae5cd94af6dbea2d4bb8dcaea8b7d215a1f/unet/diffusion_pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

What is going so wrong here? All I am doing is just importing a UNet2D from HuggingFace:
```python
flow_device = flow.device("cuda")
tmpUnet = UNet2DConditionModel.from_pretrained(
    pretrained_model_name_or_path=pretrained_model_name_or_path,
    revision=revision,
    subfolder=subfolder,
    use_auth_token=use_auth_token
).to(flow_device)
```
I've had this error before and fixed it by removing `import diffusers` and instead importing every component needed individually
I did the same here but it doesn't work, looks like something is importing it as `import diffusers`
This isn't supposed to happen however, right?

**Comment by jackalcooper** [comment]
> What is going so wrong here? All I am doing is just importing a UNet2D from HuggingFace:

For these kind of use cases, it requires a with statement like this:
```
import oneflow.mock_torch as mock
with mock.disable():
   [torch code won't be touched by oneflow]
```

**Comment by chavinlo** [comment]
> with mock.disable():

Thanks, I got to load the Unet with this.

However, when attempting to compile the graph with it It still has some conflicts specially with the scheduler:
```python
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
Exception in thread Thread-1 (image_generator):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/node/threads/base.py", line 50, in image_generator
    unet = compile(
  File "/root/node/threads/compiler.py", line 197, in compile
    unet_graph.compile(latent_model_input, t, text_embeddings)
  File "/root/env/lib/python3.10/site-packages/onediff/oneflow_graph_compile_cache.py", line 33, in compile
    self.graph_._compile(*args, **kwargs)
  File "/root/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 808, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/root/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1114, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/root/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 1228, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/root/node/threads/compiler.py", line 52, in build
    return self.unet(
  File "/root/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/env/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 449, in forward
    timesteps = torch.tensor([timesteps], dtype=dtype, device=sample.device)
TypeError: tensor(): argument 'device' must be torch.device, not oneflow._oneflow_internal.device
```

Here is the script im using: https://gist.github.com/chavinlo/e41a8e707c153b2228e0f649799c0e86
For the record, I also tried using just UnetGraph as recommendation from one of the previous issues, but that brought more problems..

**Comment by daquexian** [comment]
If you want to wrap nn.Module in nn.Graph then there is no need to use mock.disable(). Could you please provide a reproducible example of the previous problem https://github.com/Oneflow-Inc/diffusers/issues/131#issuecomment-1446270710? The script https://gist.github.com/chavinlo/e41a8e707c153b2228e0f649799c0e86 contains some 3rd libraries like .lpw and . utilities and blocks the reproduce

**Comment by chavinlo** [comment]
> If you want to wrap nn.Module in nn.Graph then there is no need to use mock.disable().
> 
> The real problem should be [#131 (comment)](https://github.com/Oneflow-Inc/diffusers/issues/131#issuecomment-1446270710). Could you please provide a reproducible example of it? The script https://gist.github.com/chavinlo/e41a8e707c153b2228e0f649799c0e86 contains some 3rd libraries like .lpw and . utilities and blocks the reproduce

Sure
While I was repackaging, for some reason it works when executed from a simple script, but not when from a thread.
[node.zip](https://github.com/Oneflow-Inc/diffusers/files/10847345/node.zip)
Here's the code, I've removed the server connection to just test the compilation and such
`main.py` is where I get the error, and is the file that I am planning to use (serves as a slave server)
`threads/test_compiler.py` works fine though, not sure what's causing it.
Had to completely uninstall `accelerate` to get rid of some weird error.

**Comment by daquexian** [comment]
@chavinlo Sorry for the late response. You should add `import onediff` at the first line of node/threads/base.py so that onediff can intercept any later `import torch`, or there will be interference between onediff and torch.
