### ISSUE TITLE
oneflow sd和torch模型如何同时运行

### ISSUE THREAD

**Issue by Nipi64310** [Oneflow-Inc/diffusers#133]
测试代码：
```
import oneflow as flow
flow.mock_torch.enable()
from transformers import AutoTokenizer,BartForConditionalGeneration,Text2TextGenerationPipeline
from diffusers import EulerDiscreteScheduler
from onediff import OneFlowStableDiffusionPipeline

model_id = "stabilityai/stable-diffusion-2"
# Use the Euler scheduler here instead
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_id, scheduler=scheduler, revision="fp16", torch_dtype=flow.float16
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt, height=768, width=768).images[0]

image.save("astronaut_rides_horse.png")

bart_tokenizer = AutoTokenizer.from_pretrained('IDEA-CCNL/Randeng-BART-139M-QG-Chinese',
                                                     additional_special_tokens=["<ans>"])
bart_model = BartForConditionalGeneration.from_pretrained('IDEA-CCNL/Randeng-BART-139M-QG-Chinese').to('cuda')
bart_pipeline = Text2TextGenerationPipeline(pr_model, pr_tokenizer,
                                                          device=0)
print(bart_pipeline ("测试", max_length=50,
                                         top_k=50, top_p=0.95,
                                         do_sample=False,
                                         num_return_sequences=1)[0]['generated_text'])

```

报错如下
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    print(bart_pipeline ("测试", max_length=50,
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/text2text_generation.py", line 165, in __call__
    result = super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1084, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1091, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/base.py", line 992, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/text2text_generation.py", line 187, in _forward
    output_ids = self.model.generate(**model_inputs, **generate_kwargs)
  File "/oneflow/python/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 1474, in generate
    return self.beam_search(
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 2809, in beam_search
    sequence_outputs = beam_scorer.finalize(
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/beam_search.py", line 336, in finalize
    sent_lengths = input_ids.new(batch_size * self.num_beam_hyps_to_keep)
AttributeError: 'Tensor' object has no attribute 'new'
```

版本
transformers  4.26.0
oneflow  0.9.1+cu118.git.7f6122c767
onediff  0.4.0

**Comment by daquexian** [comment]
Tensor.new 这个 API 刚刚在 oneflow 中实现，https://github.com/Oneflow-Inc/oneflow/pull/9881 ，可以升级最新的 oneflow nightly 重新尝试

**Comment by Nipi64310** [comment]
> stabilityai/stable-diffusion-2

Hello @daquexian ，

测试更新后上面代码没问题了，但是对比sd生成速度好像变慢了，是因为环境变量配置吗

旧版oneflow

```
path: ['/oneflow/python/oneflow']
version: 0.9.1+cu118.git.7f6122c767
git_commit: 7f6122c767
cmake_build_type: Release
rdma: False
mlir: True
```
![image](https://user-images.githubusercontent.com/31469418/222355179-072e8c3e-f252-4880-ba87-7b2f9ebc396e.png)


更新后

```
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230301+cu118
git_commit: 7548adc6
cmake_build_type: Release
rdma: True
mlir: True
```
![image](https://user-images.githubusercontent.com/31469418/222355143-1a698b13-21c3-4f5c-98a5-b6227be558eb.png)


测试代码

```python
import os

os.environ["ONEFLOW_MLIR_CSE"] = "1"
os.environ["ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION"] = "1"
os.environ["ONEFLOW_MLIR_ENABLE_ROUND_TRIP"] = "1"
os.environ["ONEFLOW_MLIR_FUSE_FORWARD_OPS"] = "1"
os.environ["ONEFLOW_MLIR_GROUP_MATMUL"] = "1"
os.environ["ONEFLOW_MLIR_PREFER_NHWC"] = "1"

os.environ["ONEFLOW_KERNEL_ENABLE_FUSED_CONV_BIAS"] = "1"
os.environ["ONEFLOW_KERNEL_ENABLE_FUSED_LINEAR"] = "1"

os.environ["ONEFLOW_KERNEL_CONV_CUTLASS_IMPL_ENABLE_TUNING_WARMUP"] = "1"
os.environ["ONEFLOW_KERNEL_CONV_ENABLE_CUTLASS_IMPL"] = "1"

os.environ["ONEFLOW_CONV_ALLOW_HALF_PRECISION_ACCUMULATION"] = "1"
os.environ["ONEFLOW_MATMUL_ALLOW_HALF_PRECISION_ACCUMULATION"] = "1"

import oneflow as torch

from onediff import OneFlowStableDiffusionPipeline as StableDiffusionPipeline
from diffusers import EulerDiscreteScheduler

"""  旧版本使用下面的import
from diffusers import OneFlowStableDiffusionPipeline as StableDiffusionPipeline, OneFlowEulerDiscreteScheduler as EulerDiscreteScheduler
"""

model_id = "stabilityai/stable-diffusion-2"
tokenizer_id = "stabilityai/stable-diffusion-2"
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(tokenizer_id, trust_remote_code=True)
# Use the Euler scheduler here instead
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16,tokenizer=tokenizer)
pipe = pipe.to("cuda")
idx = 0
for m in ['一只黄色的卡通猫咪',
        """一个小女孩"""]:
    image = pipe(m, height=768, width=768,num_inference_steps=20, guidance_scale=10).images[0]
    image.save("oneflow_{}.png".format(m[:10]))
```

**Comment by Nipi64310** [comment]
重新打包了一个镜像，速度正常了，上面测试是在之前容器里面修改版本的，再次感谢
