### ISSUE TITLE
import `transfomers` errors out

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#144]
`from transformers import CLIPTokenizer, CLIPTextModel` seems to break https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image.py

is this known, and if so how do I get the oneflow vers of CLIPTokenizer and CLIPTextModel used in `onediff`

error message 
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 734, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1071, in _load
    result = unpickler.load()
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 1064, in find_class
    return super().find_class(mod_name, name)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/mock_torch/__init__.py", line 44, in __getattr__
    raise ModuleNotFoundError(self.module.__name__ + "." + name + error_msg)
ModuleNotFoundError: oneflow._utils._rebuild_tensor_v2 is not implemented, please submit an issue at
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the
minimum reproduction code, and the system information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/text_to_image.py", line 7, in <module>
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 739, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2301, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/workspace/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/safety_checker/pytorch_model.bin' at '/workspace/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/2880f2ca379f41b0226444936bb7a6766a227587/safety_checker/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

This is on docker `oneflow/onediff:cu117`

with code 
```
from transformers import CLIPTokenizer, CLIPTextModel
import oneflow as flow

flow.mock_torch.enable()
from onediff import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)

pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with flow.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")
```

**Comment by NicholasKao1029** [comment]
The code is
```
from transformers import CLIPTokenizer, CLIPTextModel
import oneflow as flow

flow.mock_torch.enable()
from onediff import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)

pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with flow.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")
```

**Comment by NicholasKao1029** [comment]
This is on docker `oneflow/onediff:cu117`

**Comment by jackalcooper** [comment]
you need to import one diff first before importing torch based libs.

**Comment by NicholasKao1029** [comment]
Understood thank you
