### ISSUE TITLE
oneflow开启了eval $(oneflow-mock-torch)后报错

### ISSUE THREAD

**Issue by ChinaGPT** [Oneflow-Inc/diffusers#162]
oneflow开启了eval $(oneflow-mock-torch)

AUTOMATIC1111/stable-diffusion-webui执行sh webui.py报以下错误
Traceback (most recent call last):
  File "/home/m/stable-diffusion-webui/launch.py", line 381, in <module>
    start()
  File "/home/m/stable-diffusion-webui/launch.py", line 372, in start
    import webui
  File "/home/m/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/home/m/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    import modules.safe
  File "/home/m/stable-diffusion-webui/modules/safe.py", line 17, in <module>
    TypedStorage = torch.storage.TypedStorage if hasattr(torch.storage, 'TypedStorage') else torch.storage._TypedStorage
  File "/home/m/miniconda3/lib/python3.10/site-packages/oneflow/mock_torch/torch/__init__.py", line 22, in __getattr__
    return ModuleWrapper(oneflow).__getattr__(name)
  File "/home/m/miniconda3/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py", line 63, in __getattr__
    raise AttributeError(new_name + error_msg)

**Comment by Hank0626** [comment]
You need to set the `lazy` option
```
eval $(oneflow-mock-torch --lazy)
```

**Comment by ChinaGPT** [comment]
开启eval $(oneflow-mock-torch --lazy)

用你们的df2.0的测试代码报错：If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
环境：'0.9.1.dev20230320+cu117'

**Comment by daquexian** [comment]
请问你是在使用 webui 吗，oneflow 对 webui 的支持还在开发中，现在可能会遇到问题

**Comment by daquexian** [comment]
有的，可以在微信加 OneFlowXZS 好友来加入 OneFlow 用户微信群
