### ISSUE TITLE
Loading graphs from saved graphs is broken

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#174]
Trying to save and load different graphs, but am breaking when actually loading the graphs. Saving the graph does output to the path. But actually loading is problematic.

Code snippet

``` python
def setup_pipe():
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
        model_id, 
        use_auth_token=True,
        # revision="fp16",
        torch_dtype=flow.float16,
    )
    pipe = pipe.to("cuda")
    pipe.set_graph_compile_cache_size(9)
    pipe.enable_graph_share_mem()
    pipe.enable_save_graph()
    return pipe

def dumy_text_to_image(pipe, size):
    width, height = size
    images = pipe(
        "dummy",
        height=height,
        width=width,
        compile_unet=True,
        compile_vae=False,
        num_images_per_prompt=1,
        generator=flow.Generator("cuda").manual_seed(1024), # should not matter but whatevs
        output_type="np",
    ).images
    return pipe

def save_compiled_graphs(pipe, model_id, sizes, base_dir="graphs"):
    os.makedirs(base_dir, exist_ok=True)
    for size in sizes:
        width, height = size
        pipe = dumy_text_to_image(pipe, (height, width))
        graph_dir = get_graph_path(model_id, size, base_dir=base_dir)
        print("before saving graph " + str(sizes) + " " + model_id)
        pipe.save_pretrained(graph_dir)

def get_graph_path(model_id, size, base_dir="graphs"):
    width, height = size
    return os.path.join(base_dir.replace("\\", "_"), f"{model_id}_{height}x{width}")

class GraphPathManager:
    def __init__(self, base_dir="graphs"):
        self.base_dir = base_dir
        self.paths = {}

    def add(self, model_id, size):
        path = get_graph_path(model_id, size, base_dir=self.base_dir)
        if model_id not in self.paths:
            self.paths[model_id] = {}
        self.paths[model_id][size] = path

    def get(self, model_id, size):
        return self.paths[model_id][size]

# Save compiled graphs for the given sizes
print('here')
sizes_to_save = [(512, 512), (512, 768)]

start_time = time.time()
print('before setup')
pipe = setup_pipe()
print('before save compiled')
save_compiled_graphs(pipe, model_id, sizes_to_save)

print('after save compiled')
print(f"Time taken to save compiled graphs: {time.time() - start_time:.2f} seconds")

# Initialize the GraphPathManager and add paths
path_manager = GraphPathManager()
for size in sizes_to_save:
    path_manager.add(model_id, size)

# Get the graph path for a specific model_id and size
requested_model_id = model_id
requested_size = (512, 768)
graph_path = path_manager.get(requested_model_id, requested_size)
print(graph_path)

# Load the graph from the path
start_time = time.time()
pipe.load_graph(graph_path, compile_unet=True, compile_vae=False)

```

Error

```
Traceback (most recent call last):
  File "setup.py", line 119, in <module>
    pipe.load_graph(graph_path, compile_unet=True, compile_vae=False)
  File "/src/onediff/src/onediff/graph_utils.py", line 93, in load_graph
    self.graph_compile_cache.load_graph(path, graph_class2init_args)
  File "/src/onediff/src/onediff/oneflow_graph_compile_cache.py", line 162, in load_graph
    state_dict = flow.load(sub_file)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 508, in load
    return load(path, global_src_rank, map_location, *extra_data)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 410, in load_from_pytorch_file
    torch_obj = torch.load(path, map_location="cpu")
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 735, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 942, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
```

oneflow Doctor
```
root@b731ba944a82:/workspace/oneflow-server# python -m oneflow --doctor
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230325+cu117
git_commit: 0571bff
cmake_build_type: Release
rdma: True
mlir: True
```

`ls` in graph folder
```
total 4
drwxr-xr-x 9 root root 154 Apr  4 07:00 .
drwxr-xr-x 4 root root  54 Apr  4 07:00 ..
drwxr-xr-x 2 root root  38 Apr  4 07:00 feature_extractor
-rw-r--r-- 1 root root 586 Apr  4 07:46 model_index.json
drwxr-xr-x 2 root root  50 Apr  4 07:00 safety_checker
drwxr-xr-x 2 root root  35 Apr  4 07:00 scheduler
drwxr-xr-x 2 root root  50 Apr  4 07:00 text_encoder
drwxr-xr-x 2 root root 102 Apr  4 07:00 tokenizer
drwxr-xr-x 2 root root  60 Apr  4 07:00 unet
drwxr-xr-x 2 root root  60 Apr  4 07:00 vae
```

**Comment by strint** [comment]
```
File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 508, in load
    return load(path, global_src_rank, map_location, *extra_data)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 410, in load_from_pytorch_file
    torch_obj = torch.load(path, map_location="cpu")
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 735, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 942, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
```
@daquexian seems a compatibility problem in load ?

**Comment by NicholasKao1029** [comment]
Any updates @strint

**Comment by strint** [comment]
```
File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 508, in load
    return load(path, global_src_rank, map_location, *extra_data)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py", line 410, in load_from_pytorch_file
    torch_obj = torch.load(path, map_location="CPU")
```

torch.load is called, is this expected ?

**Comment by strint** [comment]
@NicholasKao1029 You can try to update the oneflow version.

```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
```

**Comment by NicholasKao1029** [comment]
kk I"ll try

**Comment by NicholasKao1029** [comment]
latest version does not work, same issue. 

I'm running this on a docker container `oneflowinc-onediff-cu117`

**Comment by daquexian** [comment]
Thanks for your issue. A json file "model_index.json" is in your graph directory and an error occurs when `flow.load` tries to load it. Please try saving graphs into an empty directory.

**Comment by NicholasKao1029** [comment]
Right, can you explain the difference between `save_pretrained` and `save_graph` I see this is my issue

**Comment by NicholasKao1029** [comment]
Made progress with the bug, now getting a core dump 

```
F20230408 08:16:59.114681  2818 buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second
*** Check failure stack trace: ***
    @     0x7f1c85a0fc9a  google::LogMessage::Fail()
    @     0x7f1c85a12bd1  google::LogMessage::SendToLog()
    @     0x7f1c85a0f7c9  google::LogMessage::Flush()
    @     0x7f1c85a134b9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1c7d8d097f  oneflow::BufferMgr<>::NewBuffer()
    @     0x7f1c7d8ae4fa  oneflow::NNGraph::NewRuntimeBuffers()
    @     0x7f1c7d8c98aa  oneflow::NNGraph::InitRuntime()
    @     0x7f1d6e7fa0d3  (unknown)
    @     0x7f1d6e668bda  (unknown)
    @     0x559caed7de7e  PyCFunction_Call
    @     0x559caed66631  _PyObject_MakeTpCall
    @     0x559caed7dbfd  method_vectorcall
    @     0x559caed61ffc  _PyEval_EvalFrameDefault
    @     0x559caed5cb76  _PyEval_EvalCodeWithName
    @     0x559caed7d85c  method_vectorcall
    @     0x559caed61ffc  _PyEval_EvalFrameDefault
    @     0x559caed6e2a6  _PyFunction_Vectorcall
    @     0x559caed5dd9d  _PyEval_EvalFrameDefault
    @     0x559caed5c461  _PyEval_EvalCodeWithName
    @     0x559caed6e33c  _PyFunction_Vectorcall
    @     0x559caed5dd9d  _PyEval_EvalFrameDefault
    @     0x559caed5c461  _PyEval_EvalCodeWithName
    @     0x559caed7d85c  method_vectorcall
    @     0x559caed5e808  _PyEval_EvalFrameDefault
    @     0x559caed5c461  _PyEval_EvalCodeWithName
    @     0x559caee1bde9  PyEval_EvalCodeEx
    @     0x559caee1bdab  PyEval_EvalCode
    @     0x559caee3c903  run_eval_code_obj
    @     0x559caee3b8e3  run_mod
    @     0x559caecdbf2f  pyrun_file
    @     0x559caecdba23  PyRun_SimpleFileExFlags
    @     0x559caeccf0ac  Py_RunMain.cold
Aborted (core dumped)
```

This happens on the `pipe.load_graph` call

**Comment by strint** [comment]
> buffer_manager.h:31] Check failed: name2buffer_.emplace

Please refer to is issue: https://github.com/Oneflow-Inc/oneflow/issues/9898

**Comment by NicholasKao1029** [comment]
Link to test showing example is broken 

https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/test/expensive/test_graph_multi_graph.py#L359

is there another?

**Comment by NicholasKao1029** [comment]
Curious why the example code here 
https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py
doesn't require saving in the same process?

**Comment by NicholasKao1029** [comment]
curious question What does it mean to have a `pipe` that was preloaded from a `model_id="something/A"` and then load a `graph` that was pre-compiled from a different model e.g. `model_id="something/B`.

e.g.
```
pipe.save_pretrained("./a") # pipe loaded from `something/A` 
pipe.save_graph("./a_graph")

another_pipe.save_pretrained("./b") # pipe loaded from `something/B`
another_pipe.save_graph("./b_graph")

...

pipe.load_graph("./b_graph") # What happens here?

```

**Comment by NicholasKao1029** [comment]
Script had hidden multi thread properties, closing

**Comment by NicholasKao1029** [comment]
> curious question What does it mean to have a `pipe` that was preloaded from a `model_id="something/A"` and then load a `graph` that was pre-compiled from a different model e.g. `model_id="something/B`.
> 
> e.g.
> 
> ```
> pipe.save_pretrained("./a") # pipe loaded from `something/A` 
> pipe.save_graph("./a_graph")
> 
> another_pipe.save_pretrained("./b") # pipe loaded from `something/B`
> another_pipe.save_graph("./b_graph")
> 
> ...
> different_pipe.from_pretrained("a")
> different_pipe.load_graph("./b_graph") # What happens here?
> ```

Tested and saw that it just followed what was put into "from_pretrained" will further test to see if this is the case
