### ISSUE TITLE
Diffusers 0.15 new features!

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#189]
Diffusers 0.15 is out and theres a ton of new features
https://github.com/huggingface/diffusers/releases/tag/v0.15.0

But juiciest is the loading of [loras](https://github.com/huggingface/diffusers/releases/tag/v0.15.0#:~:text=%5BLoRA%5D%20Enabling%20limited%20LoRA%20support%20for%20text%20encoder%20by%20%40sayakpaul%20in%20%232918) and [embeds](https://github.com/huggingface/diffusers/releases/tag/v0.15.0#:~:text=Textual%20Inversion%2C%20Revisited) more easily, 
an essential part of the auto1111 workflow that diffusers has now caught up with

Would it be possible to get these upgrades for onediff, this would make a big difference in usability

**Comment by Hank0626** [comment]
I will try it later

**Comment by Hank0626** [comment]
@NicholasKao1029 
It has supported the lora now:
* First, upgrade your diffusers to 0.15.0 by
```
python3 -m pip install "torch<2" "transformers>=4.26" "diffusers[torch]==0.15.0"
```
* Then try the following example:
```python
import oneflow as flow
flow.mock_torch.enable()
from onediff import OneFlowStableDiffusionPipeline
from typing import get_args     # add this
from diffusers.models.attention_processor import AttentionProcessor   #  # add this

for processor_type in get_args(AttentionProcessor):   # add this
    processor_type.forward = processor_type.__call__   # add this

model_path = "CompVis/stable-diffusion-v1-4"
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_path,
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)
pipe.unet.load_attn_procs("your/train/lora/model/path")

pipe = pipe.to("cuda")

for i in range(100):
    prompt = "a photo of sks dog"
    with flow.autocast("cuda"):
        images = pipe(prompt).images
        for j, image in enumerate(images):
            image.save(f"{i}.png")
```

* For how to use oneflow's libai to train lora model, refer to this https://github.com/Oneflow-Inc/libai/tree/main/projects/Stable_Diffusion#inference-with-trained-model

**Comment by NicholasKao1029** [comment]
Amazing will try asap

**Comment by NicholasKao1029** [comment]
Hiya @Hank0626, sorry I misled you. The upgrade is for this (load_lora_weights)[https://huggingface.co/docs/diffusers/v0.15.0/en/api/loaders#diffusers.loaders.LoraLoaderMixin.load_lora_weights] function that allows for a local `safetensors` lora to be loaded in, without the diffusers format

**Comment by Hank0626** [comment]
Do you mean to ask if the new diffusers' pipeline has support for the load_lora_weights function, and whether this support extends to onediff as well?

**Comment by NicholasKao1029** [comment]
yes thats right

**Comment by NicholasKao1029** [comment]
Diffusers is actually having an issue currently so it might be best to hold off, being tracked [here](https://github.com/huggingface/diffusers/issues/3064)

**Comment by NicholasKao1029** [comment]
> Do you mean to ask if the new diffusers' pipeline has support for the `load_lora_weights` function, and whether this support extends to onediff as well?

Hiya is there any plans to support this

**Comment by Hank0626** [comment]
Do you try to use `flow.mock_torch.enable(lazy=True)` and try `load_lora_weights` directly?

**Comment by NicholasKao1029** [comment]
I will try

**Comment by NicholasKao1029** [comment]
This doesn't work 

```
import oneflow as flow
from onediff import OneFlowStableDiffusionPipeline

flow.mock_torch.enable(lazy=True)
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "model",
    use_auth_token=True,
    # revision="fp16",
    torch_dtype=flow.float16,
)
pipe = pipe.to("cuda")
pipe.load_lora_weights("./lora/lora.safetensors", lora_weight=1.0)
print("lora loaded")

pipe(
    prompt="masterpiece",
    negative_prompt='ugly',
    height=768,
    width=512,
    num_inference_steps=45,
    guidance_scale=7,
    compile_vae=False,
).images

print("post pipe call")
```

gets this

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    pipe.load_lora_weights("./lora/lora.safetensors", lora_weight=1.0)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 138, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'OneFlowStableDiffusionPipeline' object has no attribute 'load_lora_weights'
Stack trace (most recent call last) in thread 11255:
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f765a18987f, in
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f765331a1b7, in
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f7653319c4c, in
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76533145c8, in vm::ThreadCtx::TryReceiveAndRun()
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f765330de3d, in vm::StreamPolicy::RunIf(vm::Instruction*) const
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76532dbd44, in vm::EpStreamPolicyBase::Run(vm::Instruction*) const
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76532ddb88, in vm::Instruction::Compute()
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76532dfebc, in vm::OpCallInstructionPolicy::Compute(vm::Instruction*)
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76532df7ab, in
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f76532e3e57, in vm::OpCallInstructionUtil::Compute(vm::OpCallInstructionPolicy*, vm::Stream*, bool, bool)
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f7651a74f47, in vm::EpStreamPolicyBase::stream()
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f764e028e03, in ep::CudaDevice::CreateStream()
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f764e02f2cd, in ep::CudaStream::CudaStream(ep::CudaDevice*)
   Object "/opt/conda/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-e31fafbe.so", at 0x7f764c5591a0, in
```

upgraded to diffusers 0.16.1

**Comment by Hank0626** [comment]
I see, this issue should be caused by the onediff pipeline not keeping up with the diffusers pipeline update. The same with https://github.com/Oneflow-Inc/diffusers/issues/166. I will make the upgrade asap.

**Comment by NicholasKao1029** [comment]
Amazing cant wait!

**Comment by Hank0626** [comment]
Try this:
```python
import oneflow as flow
from onediff import OneFlowStableDiffusionPipeline

flow.mock_torch.enable(lazy=True)
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    # revision="fp16",
    torch_dtype=flow.float16,
)
pipe = pipe.to("cuda")
pipe.load_lora_weights("patrickvonplaten/lora_dreambooth_dog_example", lora_weight=1.0)
print("lora loaded")
prompt = "a photo of one dreambooth dog"
images = pipe(
    prompt=prompt,
    height=512,
    width=512,
    num_inference_steps=45,
    guidance_scale=7,
    compile_unet=False,      # set unet graph compile to false
).images

print("post pipe call")
for i, image in enumerate(images):
    image.save(f"{prompt}-of-{i}.png")
```
Basicaly, onediff can support lora now, however it has some problem when setting the compile_unet to True (i.e. do the graph acceleration). We will fix it asap.

**Comment by NicholasKao1029** [comment]
very cool excited to see the acceleration!

**Comment by NicholasKao1029** [comment]
First I tried `patrickvonplaten/lora_dreambooth_dog_example` but it's reference does not exist in huggingface anymore. 

Then I tried (this)[https://huggingface.co/souljoy/sd-pokemon-model-lora-zh]
got this error

```bash
W20230509 07:35:53.574170 18028 cuda_stream.cpp:48] Runtime version 8.4 of cuDNN incompatible with compiletime version 8.5.
/src/onediff/src/onediff/pipeline_stable_diffusion_oneflow.py:659: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels
[ERROR](GRAPH:VaeGraph_0:VaeGraph) building graph got error.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /workspace/oneflow-server/basic.py:15 in <module>                                                │
│                                                                                                  │
│   12 pipe.load_lora_weights("souljoy/sd-pokemon-model-lora-zh", lora_weight=1.0)                 │
│   13 print("lora loaded")                                                                        │
│   14 prompt = "a picture of a temp"                                                              │
│ ❱ 15 images = pipe(                                                                              │
│   16 │   prompt=prompt,                                                                          │
│   17 │   height=512,                                                                             │
│   18 │   width=512,                                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py:154 in wrapper          │
│                                                                                                  │
│   151 │   def __call__(self, func):                                                              │
│   152 │   │   def wrapper(*args, **kwargs):                                                      │
│   153 │   │   │   with AutoGradMode(False):                                                      │
│ ❱ 154 │   │   │   │   return func(*args, **kwargs)                                               │
│   155 │   │                                                                                      │
│   156 │   │   return wrapper                                                                     │
│   157                                                                                            │
│                                                                                                  │
│ /src/onediff/src/onediff/pipeline_stable_diffusion_oneflow.py:675 in __call__                    │
│                                                                                                  │
│   672 │   │   if compile_vae:                                                                    │
│   673 │   │   │   vae_post_process_graph = self.get_graph("vae", self.vae)                       │
│   674 │   │   │   if vae_post_process_graph.is_compiled is False:                                │
│ ❱ 675 │   │   │   │   vae_post_process_graph._compile(latents)                                   │
│   676 │   │                                                                                      │
│   677 │   │   # compile unet graph                                                               │
│   678 │   │   if compile_unet:                                                                   │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py:835 in _compile                 │
│                                                                                                  │
│    832 │                                                                                         │
│    833 │   def _compile(self, *args, **kwargs):                                                  │
│    834 │   │   if self._run_with_cache == True:                                                  │
│ ❱  835 │   │   │   return self._dynamic_input_graph_cache._compile(*args, **kwargs)              │
│    836 │   │                                                                                     │
│    837 │   │   if not self._is_compiled:                                                         │
│    838 │   │   │   if not self._build_with_shared_graph:                                         │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/cache.py:120 in _compile                 │
│                                                                                                  │
│   117 │   def _compile(self, *args, **kwargs):                                                   │
│   118 │   │   graph = self.get_graph(*args, **kwargs)                                            │
│   119 │   │   with AvoidRecursiveCacheCall(graph):                                               │
│ ❱ 120 │   │   │   return graph._compile(*args, **kwargs)                                         │
│   121 │                                                                                          │
│   122 │   def runtime_state_dict(                                                                │
│   123 │   │   self, destination=None, with_eager=False,                                          │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py:839 in _compile                 │
│                                                                                                  │
│    836 │   │                                                                                     │
│    837 │   │   if not self._is_compiled:                                                         │
│    838 │   │   │   if not self._build_with_shared_graph:                                         │
│ ❱  839 │   │   │   │   return self._compile_new(*args, **kwargs)                                 │
│    840 │   │   │   else:                                                                         │
│    841 │   │   │   │   return self._compile_from_shared(*args, **kwargs)                         │
│    842 │   │   else:                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py:858 in _compile_new             │
│                                                                                                  │
│    855 │   │   │   self._is_simple_tuple_input = True                                            │
│    856 │   │                                                                                     │
│    857 │   │   self.__ensure_input_tensors_contiguous(*args, **kwargs)                           │
│ ❱  858 │   │   _, eager_outputs = self.build_graph(*args, **kwargs)                              │
│    859 │   │   if isinstance(eager_outputs, (tuple, list)) and all(                              │
│    860 │   │   │   isinstance(arg, Tensor) for arg in eager_outputs                              │
│    861 │   │   ):                                                                                │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py:1258 in build_graph             │
│                                                                                                  │
│   1255 │   │   │   │   self._debug_max_py_stack_depth,                                           │
│   1256 │   │   │   │   self._debug_only_user_py_stack,                                           │
│   1257 │   │   │   ):                                                                            │
│ ❱ 1258 │   │   │   │   outputs = self.__build_graph(*args, **kwargs)                             │
│   1259 │   │   │   build_graph_end = time.perf_counter()                                         │
│   1260 │   │   │   self.__print(                                                                 │
│   1261 │   │   │   │   0,                                                                        │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py:1375 in __build_graph           │
│                                                                                                  │
│   1372 │   │   │   # Deal with module in self.build(*args)                                       │
│   1373 │   │   │   self.__print(0, 1, self._shallow_repr() + " start building graph modules.")   │
│   1374 │   │   │   self._is_user_mode = True                                                     │
│ ❱ 1375 │   │   │   outputs = self.build(*lazy_args, **lazy_kwargs)                               │
│   1376 │   │   │   self._is_user_mode = False                                                    │
│   1377 │   │   │   self.__print(0, 1, self._shallow_repr() + " end building graph modules.")     │
│   1378                                                                                           │
│                                                                                                  │
│ /src/onediff/src/onediff/graph_utils.py:37 in build                                              │
│                                                                                                  │
│    34 │   │   │   self.config.allow_fuse_add_to_output(True)                                     │
│    35 │   │                                                                                      │
│    36 │   │   def build(self, latents):                                                          │
│ ❱  37 │   │   │   return self.vae_post_process(latents)                                          │
│    38 │                                                                                          │
│    39 │   return VaeGraph(*args, **kwargs)                                                       │
│    40                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py:186 in __call__                 │
│                                                                                                  │
│   183 │   │   │   self.to(GraphModule)._debug_max_py_stack_depth,                                │
│   184 │   │   │   self.to(GraphModule)._debug_only_user_py_stack,                                │
│   185 │   │   ):                                                                                 │
│ ❱ 186 │   │   │   result = self.__block_forward(*args, **kwargs)                                 │
│   187 │   │                                                                                      │
│   188 │   │   outputs = ()                                                                       │
│   189 │   │   if not (type(result) is tuple or type(result) is list):                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py:236 in __block_forward          │
│                                                                                                  │
│   233 │   │   │   # the argument list."                                                          │
│   234 │   │   │   # Reference: https://docs.python.org/3/reference/datamodel.html                │
│   235 │   │   │   unbound_forward_of_module_instance = self.to(Module).forward.__func__          │
│ ❱ 236 │   │   │   result = unbound_forward_of_module_instance(self, *args, **kwargs)             │
│   237 │   │   self.to(GraphModule)._is_executing_forward = False                                 │
│   238 │   │   return result                                                                      │
│   239                                                                                            │
│                                                                                                  │
│ /src/onediff/src/onediff/graph_utils.py:49 in forward                                            │
│                                                                                                  │
│    46 │                                                                                          │
│    47 │   def forward(self, latents):                                                            │
│    48 │   │   latents = 1 / 0.18215 * latents                                                    │
│ ❱  49 │   │   image = self.vae.decode(latents).sample                                            │
│    50 │   │   image = (image / 2 + 0.5).clamp(0, 1)                                              │
│    51 │   │   return image                                                                       │
│    52                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/utils/accelerate_utils.py:46 in wrapper         │
│                                                                                                  │
│   43 │   def wrapper(self, *args, **kwargs):                                                     │
│   44 │   │   if hasattr(self, "_hf_hook") and hasattr(self._hf_hook, "pre_forward"):             │
│   45 │   │   │   self._hf_hook.pre_forward(self)                                                 │
│ ❱ 46 │   │   return method(self, *args, **kwargs)                                                │
│   47 │                                                                                           │
│   48 │   return wrapper                                                                          │
│   49                                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/models/autoencoder_kl.py:191 in decode          │
│                                                                                                  │
│   188 │   │   │   decoded_slices = [self._decode(z_slice).sample for z_slice in z.split(1)]      │
│   189 │   │   │   decoded = torch.cat(decoded_slices)                                            │
│   190 │   │   else:                                                                              │
│ ❱ 191 │   │   │   decoded = self._decode(z).sample                                               │
│   192 │   │                                                                                      │
│   193 │   │   if not return_dict:                                                                │
│   194 │   │   │   return (decoded,)                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/models/autoencoder_kl.py:178 in _decode         │
│                                                                                                  │
│   175 │   │   │   return self.tiled_decode(z, return_dict=return_dict)                           │
│   176 │   │                                                                                      │
│   177 │   │   z = self.post_quant_conv(z)                                                        │
│ ❱ 178 │   │   dec = self.decoder(z)                                                              │
│   179 │   │                                                                                      │
│   180 │   │   if not return_dict:                                                                │
│   181 │   │   │   return (dec,)                                                                  │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py:186 in __call__                 │
│                                                                                                  │
│   183 │   │   │   self.to(GraphModule)._debug_max_py_stack_depth,                                │
│   184 │   │   │   self.to(GraphModule)._debug_only_user_py_stack,                                │
│   185 │   │   ):                                                                                 │
│ ❱ 186 │   │   │   result = self.__block_forward(*args, **kwargs)                                 │
│   187 │   │                                                                                      │
│   188 │   │   outputs = ()                                                                       │
│   189 │   │   if not (type(result) is tuple or type(result) is list):                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py:236 in __block_forward          │
│                                                                                                  │
│   233 │   │   │   # the argument list."                                                          │
│   234 │   │   │   # Reference: https://docs.python.org/3/reference/datamodel.html                │
│   235 │   │   │   unbound_forward_of_module_instance = self.to(Module).forward.__func__          │
│ ❱ 236 │   │   │   result = unbound_forward_of_module_instance(self, *args, **kwargs)             │
│   237 │   │   self.to(GraphModule)._is_executing_forward = False                                 │
│   238 │   │   return result                                                                      │
│   239                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/models/vae.py:215 in forward                    │
│                                                                                                  │
│   212 │   │   sample = z                                                                         │
│   213 │   │   sample = self.conv_in(sample)                                                      │
│   214 │   │                                                                                      │
│ ❱ 215 │   │   upscale_dtype = next(iter(self.up_blocks.parameters())).dtype                      │
│   216 │   │   if self.training and self.gradient_checkpointing:                                  │
│   217 │   │   │                                                                                  │
│   218 │   │   │   def create_custom_forward(module):                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ProxyTensor' object has no attribute 'dtype'
```

Then I tried a local lora like so 

```bash
 pipe.load_lora_weights("lora/temp.safetensors", lora_weight=1.0)
```

Then got this error

```bash
warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /workspace/oneflow-server/basic.py:12 in <module>                                                │
│                                                                                                  │
│    9 │   torch_dtype=flow.float16,                                                               │
│   10 )                                                                                           │
│   11 pipe = pipe.to("cuda")                                                                      │
│ ❱ 12 pipe.load_lora_weights("lora/temp.safetensors", lora_weight=1.0)                            │
│   13 print("lora loaded")                                                                        │
│   14 prompt = "a picture of a temp"                                                              │
│   15 images = pipe(                                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/loaders.py:805 in load_lora_weights             │
│                                                                                                  │
│    802 │   │   │   │   │   subfolder=subfolder,                                                  │
│    803 │   │   │   │   │   user_agent=user_agent,                                                │
│    804 │   │   │   │   )                                                                         │
│ ❱  805 │   │   │   │   state_dict = torch.load(model_file, map_location="cpu")                   │
│    806 │   │   else:                                                                             │
│    807 │   │   │   state_dict = pretrained_model_name_or_path_or_dict                            │
│    808                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py:634 in load           │
│                                                                                                  │
│   631 │   │   │   │   err_msg = f'Cannot load file "{path}"'                                     │
│   632 │   │   │   else:                                                                          │
│   633 │   │   │   │   err_msg = "Cannot load the data"                                           │
│ ❱ 634 │   │   │   raise ValueError(err_msg)                                                      │
│   635 │   else:                                                                                  │
│   636 │   │   i = _broadcast_py_object(None, global_src_rank)                                    │
│   637 │   │   load = load_methods[i][1]                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Cannot load file "lora/temp.safetensors"
W20230509 07:33:16.007773 16193 cuda_stream.cpp:48] Runtime version 8.4 of cuDNN incompatible with compiletime version 8.5.
```

this is the doctor
```
path: ['/opt/conda/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230504+cu117
git_commit: 7c202ba
cmake_build_type: Release
rdma: True
mlir: True
```

on diffusers version `0.16.1`

**Comment by NicholasKao1029** [comment]
Thanks your example works now, (haven't verified pic output), loading from local file (safetensors) does not work, attached is the error

```bash
/opt/conda/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
lora/blah.safetensors
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /workspace/oneflow-server/test.py:53 in <module>                                                 │
│                                                                                                  │
│   50 pipe = pipe.to("cuda")                                                                      │
│   51 path = Path("./lora/blah.safetensors")                                           │
│   52 print(path)                                                                                 │
│ ❱ 53 pipe.load_lora_weights(path, lora_weight=1.0)                                               │
│   54 print("lora loaded")                                                                        │
│   55 prompt = "粉色的蝴蝶,小精灵,卡通"                                                           │
│   56 images = pipe(                                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/diffusers/loaders.py:749 in load_lora_weights             │
│                                                                                                  │
│    746 │   │   │   │   │   subfolder=subfolder,                                                  │
│    747 │   │   │   │   │   user_agent=user_agent,                                                │
│    748 │   │   │   │   )                                                                         │
│ ❱  749 │   │   │   │   state_dict = torch.load(model_file, map_location="cpu")                   │
│    750 │   │   else:                                                                             │
│    751 │   │   │   state_dict = pretrained_model_name_or_path_or_dict                            │
│    752                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/oneflow/framework/check_point_v2.py:634 in load           │
│                                                                                                  │
│   631 │   │   │   │   err_msg = f'Cannot load file "{path}"'                                     │
│   632 │   │   │   else:                                                                          │
│   633 │   │   │   │   err_msg = "Cannot load the data"                                           │
│ ❱ 634 │   │   │   raise ValueError(err_msg)                                                      │
│   635 │   else:                                                                                  │
│   636 │   │   i = _broadcast_py_object(None, global_src_rank)                                    │
│   637 │   │   load = load_methods[i][1]                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Cannot load file "lora/blah.safetensors"
```

**Comment by NicholasKao1029** [comment]
> > ```shell
> > lora/blah.safetensors
> > ```
> 
> Do you try to use original diffusers v0.15.1 to run the script?

my diffusers version is 0.15.1 if that's what you're asking

**Comment by NicholasKao1029** [comment]
Ahh you are correct it is broken for 0.15.1, actually broken for 0.16.1 as well being dealt with here in this pr and issue respectively 
https://github.com/huggingface/diffusers/pull/3294
https://github.com/huggingface/diffusers/issues/3064

**Comment by sanbuphy** [comment]
I encountered the same problem. I also want to load bin's lora in onediff. I want to this script to convert safetensors to bin and then used onediff's load API.https://github.com/huggingface/diffusers/issues/3064#issuecomment-1512429695
 Have you tried it successfully?

**Comment by NicholasKao1029** [comment]
> I encountered the same problem. I also want to load bin lora in onediff. I want to this script to convert safetensors to bin and then used onediff's load API.[huggingface/diffusers#3064 (comment)](https://github.com/huggingface/diffusers/issues/3064#issuecomment-1512429695) Have you tried it successfully?

Haven't tried yet, what issue did you run into?

**Comment by sanbuphy** [comment]
> > I encountered the same problem. I also want to load bin lora in onediff. I want to this script to convert safetensors to bin and then used onediff's load API.[huggingface/diffusers#3064 (comment)](https://github.com/huggingface/diffusers/issues/3064#issuecomment-1512429695) Have you tried it 
> >           successfully
> >           ?
> 
> Haven't tried yet, what issue did you run into?

I found it can work but it's not the optimal implementation

**Comment by sunhs** [comment]
> I think this solution may be helpful [huggingface/diffusers#3064 (comment)](https://github.com/huggingface/diffusers/issues/3064#issuecomment-1512429695)

Hi, I'm using this method with diffusers and it works well. However, when using this with onediff, the following error emerges when running the line `if len(weight_up.shape) == 4:`:

```
TypeError: object of type 'DummyModule' has no len()
```

Seems all the pytorch tensors are converted to this `DummyModule` once loaded from a safetensor. Is there any workaround that I can try ?
