### ISSUE TITLE
`python3 -m onediff.demo` crashes in docker container.

### ISSUE THREAD

**Issue by caiyesd** [Oneflow-Inc/diffusers#218]
I want to try to run OneFlow Stable Diffusion, and I follow the steps in WIKI https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#using-docker

But a crash occurs.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/src/onediff/src/onediff/__init__.py", line 26, in <module>
    from .pipeline_stable_diffusion_img2img_oneflow import (
  File "/src/onediff/src/onediff/pipeline_stable_diffusion_img2img_oneflow.py", line 44, in <module>
    from diffusers.loaders import LoraLoaderMixin, TextualInversionLoaderMixin
ImportError: cannot import name 'LoraLoaderMixin' from 'diffusers.loaders' (/opt/conda/lib/python3.8/site-packages/diffusers/loaders.py)
```

Is there anyone can help to fix it?

**Comment by caiyesd** [comment]
When I try the method without docker in https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#without-docker, another crash occurs.

```
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
/usr/local/lib/python3.10/dist-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/onediff/demo/__main__.py", line 40, in <module>
    images = pipe(args.prompt).images
  File "/usr/local/lib/python3.10/dist-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 645, in __call__
    text_embeddings = self._encode_prompt(
  File "/usr/local/lib/python3.10/dist-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 370, in _encode_prompt
    text_embeddings = self.text_encoder(
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/modules/module.py", line 225, in __call__
    res = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 816, in forward
    return self.text_model(
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/modules/module.py", line 225, in __call__
    res = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 717, in forward
    causal_attention_mask = self._build_causal_attention_mask(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py", line 760, in _build_causal_attention_mask
    mask.triu_(1)  # zero out the lower diagonal
RuntimeError: Error: kFloat16 .vs kFloat
```

**Comment by caiyesd** [comment]
@Hank0626 Thank you!
