### ISSUE TITLE
TypeError: <class 'oneflow.mock_torch.DummyModule'> is not a Module subclass

### ISSUE THREAD

**Issue by shabri-arrahim** [Oneflow-Inc/diffusers#232]
Got this error when try to running sd v2:
```
/home/ubuntu/env/lib/python3.8/site-packages/oneflow/jit/__init__.py:34: UserWarning: The oneflow.jit.ignore interface is just to align the torch.jit.ignore interface and has no practical significance.
  warnings.warn(
/home/ubuntu/env/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_img2img_oneflow.py:34: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate

.
Loading pipeline components...:  20%|██████████▌                                          | 1/5 [00:01<00:05,  1.43s/it]
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1063, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 468, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 695, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 232, in from_config
    model = cls(**init_dict)
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 614, in inner_init
    init(self, *args, **init_kwargs)
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/models/autoencoder_kl.py", line 95, in __init__
    self.encoder = Encoder(
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/models/vae.py", line 88, in __init__
    self.mid_block = UNetMidBlock2D(
  File "/home/ubuntu/env/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 504, in __init__
    self.attentions = nn.ModuleList(attentions)
  File "/home/ubuntu/env/lib/python3.8/site-packages/oneflow/nn/utils/container.py", line 110, in __init__
    self += modules
  File "/home/ubuntu/env/lib/python3.8/site-packages/oneflow/nn/utils/container.py", line 147, in __iadd__
    return self.extend(modules)
  File "/home/ubuntu/env/lib/python3.8/site-packages/oneflow/nn/utils/container.py", line 187, in extend
    self.add_module(str(offset + i), module)
  File "/home/ubuntu/env/lib/python3.8/site-packages/oneflow/nn/modules/module.py", line 266, in add_module
    raise TypeError("{} is not a Module subclass".format(type(module)))
TypeError: <class 'oneflow.mock_torch.DummyModule'> is not a Module subclass
```
I use example code for v2:
```
from onediff import OneFlowStableDiffusionPipeline

import oneflow as flow
flow.mock_torch.enable()

from diffusers import EulerDiscreteScheduler

model_id = "stabilityai/stable-diffusion-2"
# Use the Euler scheduler here instead
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_id, scheduler=scheduler, revision="fp16", torch_dtype=flow.float16
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt, height=768, width=768).images[0]

image.save("astronaut_rides_horse.png")
```

**Comment by jackalcooper** [comment]
I managed to run the code above with not problem. You might install pip packages with 
```bash
python3 -m pip install "torch" "transformers==4.27.1" "diffusers[torch]==0.15.1"
pip3 uninstall -y accelerate
```

**Comment by strint** [comment]
We are fixing this with https://github.com/Oneflow-Inc/oneflow/pull/10318.

diffusers 0.19.3 is using torch 2.0's `maybe_allow_in_graph` in torch._dynamo.
```
@maybe_allow_in_graph
class BasicTransformerBlock(nn.Module):
```

So if you are using newer version of diffusers and torch 2.0.1 which torch._dynamo is available, `oneflow.mock_torch` will raise:
```
TypeError: <class 'oneflow.mock_torch.DummyModule'> is not a Module subclass
```

**Comment by zengjie617789** [comment]
@strint  hello, why I downgrade torch version to 2.0.0 and i still got the error below:
`AttributeError: oneflow._dynamo.eval_frame is not implemented, please submit an issue at`
how can i fix it.

**Comment by strint** [comment]
> @strint hello, why I downgrade torch version to 2.0.0 and i still got the error below: `AttributeError: oneflow._dynamo.eval_frame is not implemented, please submit an issue at` how can i fix it.

Try to update your oneflow to the Nightly version:

https://github.com/Oneflow-Inc/oneflow#install-with-pip-package

**Comment by zengjie617789** [comment]
I upgraded the version of oneflow. but i still got the error. 
the version of each packages below:
>oneflow:0.9.1.dev20231009+cu117
diffusers: 0.19.3
torch:2.0.0+cu117

I will be appreciate if any help provided.

**Comment by strint** [comment]
>  why I downgrade torch version to 2.0.0 and i still got the error below: `AttributeError: oneflow._dynamo.eval_frame is not implemented, please submit an issue at` how can i fix it.

Got this. This is a different problem, please provide the full python error stack.

**Comment by zengjie617789** [comment]
@strint the screenshot is like below:
![image](https://github.com/Oneflow-Inc/diffusers/assets/25050291/71e5cc53-c0ee-43ad-9e27-cee1593cbf6b)

**Comment by strint** [comment]
Please update to the latest version: https://github.com/Oneflow-Inc/onediff?tab=readme-ov-file#install-from-source
This issue is too old to follow and will be closed. Feel free to reopen it and continue.
