### ISSUE TITLE
用 NVIDIA TITAN Xp卡跑onediff.demo时提示“The CUDA device 'NVIDIA TITAN Xp' with capability 61 is not compatible with the current OneFlow installation”

### ISSUE THREAD

**Issue by devilxie** [Oneflow-Inc/diffusers#252]
系统环境是ubuntu 20.04,  python3.8.10, 安装cuda11.8, torch==2.0.0+cu118
安装oneflow-0.9.1.dev20230914%2Bcu118-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl， 指令如下：
pip install --pre oneflow -f https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu118

按照教程运行onediff.demo时，有如下提示：

W20230915 21:28:40.715044 2569473 cuda_device_descriptor.cpp:91] The CUDA device 'NVIDIA TITAN Xp' with capability 61 is not compatible with the current OneFlow installation. The current program may throw a 'no kernel image is available for execution on the device' error or hang for a long time. Please reinstall OneFlow compiled with a newer version of CUDA.

整个运行过程最后果然失败了，崩溃信息如下：

/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py:658: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels
terminate called after throwing an instance of 'oneflow::RuntimeException'
  what():  Error: no kernel image is available for execution on the device (209)
You can set ONEFLOW_DEBUG or ONEFLOW_PYTHON_STACK_GETTER to 1 to get the Python stack of the error.
Stack trace (most recent call last) in thread 2569649:
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fe0dd8a8f, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d4b177, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d4abc7, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d459e8, in vm::ThreadCtx::TryReceiveAndRun()
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d3f62d, in vm::StreamPolicy::RunIf(vm::Instruction*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d0cb34, in vm::EpStreamPolicyBase::Run(vm::Instruction*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d0e978, in vm::Instruction::Compute()
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d10fbc, in vm::OpCallInstructionPolicy::Compute(vm::Instruction*)
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d108eb, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd9d14f49, in vm::OpCallInstructionUtil::Compute(vm::OpCallInstructionPolicy*, vm::Stream*, bool, bool)
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fdca628fb, in StatefulOpKernel::Compute(eager::CallContext*, ep::Stream*, user_op::OpKernel const*, user_op::OpKernelState*, user_op::OpKernelCache const*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fdca6170a, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-fd5157a3.so", at 0x7f4fd1f88e27, in

Aborted (Signal sent by tkill() 2569473 17279)

**Comment by jackalcooper** [comment]
请试试看cu117

**Comment by devilxie** [comment]
那是否说明上面cu118的版本是未验证过的吗？
原机器已安装cu118, 本想偷懒跳过cu117的安装这一步

**Comment by jackalcooper** [comment]
118版因为体积太大，去除了比较早的版本的cuda二进制

**Comment by devilxie** [comment]
有什么其它办法修正这个问题吗？

**Comment by jackalcooper** [comment]
> 有什么其它办法修正这个问题吗？

必须要用cu118的原因是🤔

**Comment by devilxie** [comment]
好吧，我换成了cu117的版本，还是崩溃了

/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/onediff/pipeline_stable_diffusion_oneflow.py:658: FutureWarning: Accessing config attribute `in_channels` directly via 'UNet2DConditionModel' object attribute is deprecated. Please access 'in_channels' over 'UNet2DConditionModel's config object instead, e.g. 'unet.config.in_channels'.
  num_channels_latents = self.unet.in_channels


  0%|                                                                                                                                                                             | 0/50 [00:00<?, ?it/s]terminate called after throwing an instance of 'oneflow::Exception'
  what():  Check failed: (operation != nullptr)
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in Thread::PollMsgChannel()
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in Kernel::Launch(KernelContext*) const
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in Kernel::Forward(KernelContext*) const
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in UserKernel::ForwardDataContent(KernelContext*) const
  File "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", line <unknown>, in UserKernel::ForwardUserKernel(std::function<Blob* (std::string const&)> const&, user_op::OpKernelState*) const
  File "oneflow/user/kernels/conv_cutlass_kernels.cu", line 155, in Compute
    CHECK_OR_THROW(operation != nullptr)
Error Type: oneflow.ErrorProto.check_failed_error
Stack trace (most recent call last) in thread 1009735:
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdf1a27a6f, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdea94108d, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdea93fbd7, in Thread::PollMsgChannel()
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdea2200b3, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efde9ec8d98, in Kernel::Launch(KernelContext*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efde9ec87c2, in Kernel::Forward(KernelContext*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efde9f0725a, in UserKernel::ForwardDataContent(KernelContext*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efde9f0705e, in UserKernel::ForwardUserKernel(std::function<Blob* (std::string const&)> const&, user_op::OpKernelState*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdeaf5acaa, in (anonymous namespace)::Conv2dCutlassKernel::Compute(user_op::KernelComputeContext*, user_op::OpKernelState*, user_op::OpKernelCache const*) const
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efdeaf52b6c, in
   Object "/data2/sdk/oneflow_py3.8/lib/python3.8/site-packages/oneflow/../oneflow.libs/liboneflow-dc781e3a.so", at 0x7efde2be1f24, in

Aborted (Signal sent by tkill() 1009361 17279)
[1]    1009361 abort (core dumped)  python3 -m onediff.demo

**Comment by jackalcooper** [comment]
@devilxie 很抱歉，这个是kernel不支持😭。目前来看现在的这个sd实现需要运行在 Compute capability>=7.0 的 CUDA GPU，Nvidia TITAN Xp 是 6.1。

**Comment by devilxie** [comment]
有低一点的oneflow版本支持 Nvidia TITAN Xp GPU吗？

**Comment by jackalcooper** [comment]
> 有低一点的oneflow版本支持 Nvidia TITAN Xp GPU吗？

oneflow cu117本身是支持的，但是 oneflow 版本的 sd 用到了 TITAN Xp 不支持的 kernel

**Comment by devilxie** [comment]
换了一台电脑，安装oneflow cu118,  运行过程没看到问题，但最终跑出来的图'a photo of an astronaut riding a horse on mars-0-0.png'是一张全灰图

**Comment by jackalcooper** [comment]
> 换了一台电脑，安装oneflow cu118, 运行过程没看到问题，但最终跑出来的图'a photo of an astronaut riding a horse on mars-0-0.png'是一张全灰图

啊，可以帮忙试试看我们现在正在新开发的版本吗

- setup a python 3.10 environment
- you might install latest oneflow nightly with
```
python3 -m pip install --pre oneflow -f https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu117
```
- and check out onediff’s `refactor-backend` branch
```
git clone https://github.com/Oneflow-Inc/diffusers.git onediff
cd onediff
git checkout refactor-backend
python3 -m pip install “torch” “diffusers[torch]”
python3 -m pip uninstall accelerate -y
python3 -m pip install -e .
```
- and run the example
	- (note: you might want to change the resolution and num_inference_steps)
```
python3 examples/text_to_image_sdxl_fp16.py --graph --compile --model stabilityai/stable-diffusion-xl-base-1.0
```

**Comment by devilxie** [comment]
按这个操作过，最后出现一个错误，看起来你们对torch的版本也有依赖，我安装的torch是1.13.0+cu117

Traceback (most recent call last):
  File "/data/sources/onediff/examples/text_to_image_sdxl_fp16.py", line 53, in <module>
    pipe.unet = torch.compile(pipe.unet, fullgraph=True, mode="reduce-overhead", backend=torchbackend)
AttributeError: module 'torch' has no attribute 'compile'

**Comment by jackalcooper** [comment]
> 按这个操作过，最后出现一个错误，看起来你们对torch的版本也有依赖，我安装的torch是1.13.0+cu117
> 
> Traceback (most recent call last): File "/data/sources/onediff/examples/text_to_image_sdxl_fp16.py", line 53, in pipe.unet = torch.compile(pipe.unet, fullgraph=True, mode="reduce-overhead", backend=torchbackend) AttributeError: module 'torch' has no attribute 'compile'

哦哦，新版的实现需要torch2

**Comment by devilxie** [comment]
换了torch 2.0.1+cu117版本，运行后还是崩溃了，出现oneflow.fx有不支持的属性
Traceback (most recent call last):
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/data/sources/onediff/src/onediff/infer_compiler/__init__.py", line 16, in torchbackend
    transformed_fn = fx_node_tranform(gm)
  File "/data/sources/onediff/src/onediff/infer_compiler/with_fx_graph.py", line 10, in fx_node_tranform
    of_gm = to_of_transform(gm)
  File "/data/sources/onediff/src/onediff/infer_compiler/with_fx_graph.py", line 43, in to_of_transform
    of_g = flow.fx.Graph()
AttributeError: module 'oneflow.fx' has no attribute 'Graph'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/sources/onediff/examples/text_to_image_sdxl_fp16.py", line 58, in <module>
    image = pipe(prompt=args.prompt, height=96, width=128, num_inference_steps=50).images[0]
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 814, in __call__
    noise_pred = self.unet(
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xiewenbiao/sdk/oneflow_py3.10/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: torchbackend raised AttributeError: module 'oneflow.fx' has no attribute 'Graph'

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

**Comment by devilxie** [comment]
很遗憾，目前在多台机器上搭建的oneflow环境都无法产生预期的收益，或是运行异常，或是版本兼容性问题，或是onediff.demo运行结果完全不对。而且能正常运行完的流程整体耗时相对torch版本还要更长，如下一测试用例：

run_sd_pipeline_with_oneflow elapsed time: 102.27772377 s
run_sd_pipeline_with_torch elapsed time: 44.29621943 s

**Comment by jackalcooper** [comment]
> 能正常运行完的流程整体耗时相对torch版本还要更长

这是因为编译优化的耗时？

**Comment by strint** [comment]
这个版本已经过时，更新到最新版本一个可以获得最新的优化。

This issue is too old to follow and will be closed. Feel free to reopen it and continue.
