### ISSUE TITLE
0.9.1动态分辨率报错

### ISSUE THREAD

**Issue by cjt222** [Oneflow-Inc/diffusers#334]
你好，我用最新的0.9.1-cuda12.1的版本，发现不支持动态分辨率，一旦修改分别率输入后会报错
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1786, in _execute
    result = await result
  File "/workspace/app/views.py", line 196, in post
    res = glo_engine.run(
  File "/workspace/app/utils.py", line 27, in wrapper
    res = fun(*args, **kwargs)
  File "/workspace/app/infer/pipeline.py", line 50, in run
    sd_output = self.pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/lib/diffusers_extra/diffusers_extra/pipelines/stable_diffusion/pipeline_stable_diffusion_xl_llm.py", line 764, in __call__
    noise_pred = self.unet(
  File "/workspace/lib/onediff/diffusers/src/onediff/infer_compiler/with_oneflow_compile.py", line 123, in __call__
    output = dpl_graph(*mapped_args, **mapped_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 281, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/cache.py", line 115, in __call__
    return graph(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 284, in __call__
    self._compile(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 854, in _compile
    return self._compile_from_shared(*args, **kwargs)
2023-11-10 08:10:23,578 ERROR | 500 POST /text2image (127.0.0.6) 3347.34ms - 48d5e1f8-25b5-48cc-9dee-1e8472b951eb
  File "/usr/local/lib/python3.10/dist-packages/oneflow/nn/graph/graph.py", line 976, in _compile_from_shared
    self._c_nn_graph.build_with_new_input_from_shared_graph(
oneflow._oneflow_internal.exception.RuntimeError: Error: Check failed: ((2,1280) == (8,1280))

**Comment by strint** [comment]
pipeline 那里你只改了分辨率么，可以发下你输入的例子看看

**Comment by strint** [comment]
Duplicated with: https://github.com/Oneflow-Inc/diffusers/issues/337
