### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by Amber0130** [Oneflow-Inc/diffusers#378]
ERROR [2023-11-28 13:28:13] - Exception in __call__: e=TypeError('super(type, obj): obj must be an instance or subtype of type')
  0%|                                                                                                                                                    | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 127, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 190, in __call__
    dpl_graph = self.get_graph()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 164, in get_graph
    self._deployable_module_model.oneflow_module, size
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 28, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 225, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 195, in init
    self._modules[n] = torch2oflow(m)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 246, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 225, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 185, in init
    flow.nn.Module.__init__(self)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/zhangshichen/oneflowdemo/oneflow/main.py", line 23, in <module>
    api = create_api(app)
  File "/home/ubuntu/zhangshichen/oneflowdemo/oneflow/main.py", line 16, in create_api
    from tools.api import Api
  File "/home/ubuntu/zhangshichen/oneflowdemo/oneflow/tools/api.py", line 65, in <module>
    Txt2imgpipe( prompt="people",
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 840, in __call__
    noise_pred = self.unet(
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/utils/args_tree_util.py", line 34, in wrapper
    output = func(cls, *mapped_args, **mapped_kwargs)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 133, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 190, in __call__
    dpl_graph = self.get_graph()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 164, in get_graph
    self._deployable_module_model.oneflow_module, size
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/with_oneflow_compile.py", line 28, in oneflow_module
    self._oneflow_module = torch2oflow(self._torch_module)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 225, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 195, in init
    self._modules[n] = torch2oflow(m)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 246, in _
    submod = torch2oflow(original_submod, verbose)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 38, in wrapper
    result = dispatcher(first_param, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 225, in _
    of_mod = of_mod_cls()
  File "/home/ubuntu/zhangshichen/onediff/src/onediff/infer_compiler/transform/builtin_transform.py", line 185, in init
    flow.nn.Module.__init__(self)
  File "/home/ubuntu/anaconda3/envs/new/lib/python3.9/site-packages/oneflow/nn/modules/module.py", line 150, in __init__
    super().__setattr__("training", True)
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by strint** [comment]
Please paste your diffusers version here.

**Comment by Amber0130** [comment]
> Please paste your diffusers version here.
> 
> We has tested this on diffusers 0.19.3. Newer version will be supported soon.

已经解决啦

**Comment by strint** [comment]
diffusers 0.22 and 0.23 are supported now. Please:
- update oneflow by re-install https://github.com/Oneflow-Inc/diffusers#install-from-source
- update onediff by pull the new main branch.

**Comment by Amber0130** [comment]
> diffusers 0.22 and 0.23 are supported now. Please:
> 
> * update OneFlow by re-install https://github.com/Oneflow-Inc/diffusers#install-from-source
> * update OneDiff by pull the new main branch.

🙏🙏
