### ISSUE TITLE
运行img2img ValueError: torch.float16 needs to be of type `torch.dtype`, e.g. `torch.float16`, but is <class 'torch.dtype'>.

### ISSUE THREAD

**Issue by zshfeng00** [Oneflow-Inc/diffusers#69]
### Describe the bug

运行img2img时，加载模型有报错

### Reproduction

import requests
import torch
from PIL import Image
from io import BytesIO

#from diffusers import StableDiffusionImg2ImgPipeline
from diffusers import OneFlowStableDiffusionImg2ImgPipeline as StableDiffusionImg2ImgPipeline

# load the pipeline
device = "cuda"
model_id_or_path = "stabilityai/stable-diffusion-2-1"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16)

# or download via git clone https://huggingface.co/runwayml/stable-diffusion-v1-5
# and pass `model_id_or_path="./stable-diffusion-v1-5"`.
generator = torch.Generator("cuda").manual_seed(42)
pipe = pipe.to(device)

# let's download an initial image
url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"

response = requests.get(url)
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image = init_image.resize((768, 512))

prompt = "A fantasy landscape, trending on artstation"

images = pipe(prompt=prompt, generator=generator, image=init_image, strength=0.75, guidance_scale=7.5).images

### Logs

```shell
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 25940.81it/s]
The config attributes {'upcast_attention': True} were passed to OneFlowUNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "sd-i.py", line 13, in <module>
    pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16)
  File "/root/zsf/oneflow/diffusers/src/diffusers/pipeline_oneflow_utils.py", line 706, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/root/zsf/oneflow/diffusers/src/diffusers/modeling_oneflow_utils.py", line 518, in from_pretrained
    raise ValueError(
ValueError: torch.float16 needs to be of type `torch.dtype`, e.g. `torch.float16`, but is <class 'torch.dtype'>.
```

### System Info

.......

**Comment by zshfeng00** [comment]
solved
