### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Yanting-K** [Oneflow-Inc/diffusers#8]
### Describe the bug

The conv_out weight and bias have AssertionError

### Reproduction

While copying the parameter "conv_out.weight", an exception occurred : 

        Traceback (most recent call last):
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/nn/module.py", line 788, in 
_load_from_state_dict
            param.copy_(input_param)
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 341, 
in _copy
            _copy_from_numpy_to_eager_local_tensor(self, other)
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 290, 
in _copy_from_numpy_to_eager_local_tensor
            assert np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype(
        AssertionError
.
        While copying the parameter "conv_out.bias", an exception occurred : 

        Traceback (most recent call last):
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/nn/module.py", line 788, in 
_load_from_state_dict
            param.copy_(input_param)
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 341, 
in _copy
            _copy_from_numpy_to_eager_local_tensor(self, other)
          File "/home/kang/anaconda3/envs/kyt/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 290, 
in _copy_from_numpy_to_eager_local_tensor
            assert np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype(
        AssertionError

### System Info

diffusers-cli env
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.3.0-050300rc1-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.10.1+cu111 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by Yanting-K** [comment]
Should I complite my environment to cuda11.2?

**Comment by jackalcooper** [comment]
what is your oneflow version?

**Comment by ltm920716** [comment]
@jackalcooper 
oneflow                 0.8.1+cu102.git.5610333

**Comment by Yanting-K** [comment]
my oneflow 0.8.1+cu112.git.5610333 
gpu:3090

**Comment by Yipeng1994** [comment]
It might be a known fixed bug. 
Could you try to pull the newest oneflow? @Yanting-K @ltm920716

**Comment by Yanting-K** [comment]
pull the new oneflow's diffusers and complete it, but doesn't solve this question. My pytorch environment is cuda11.3, but oneflow is cu112

**Comment by 5118Python** [comment]
same question
`While copying the parameter "conv_out.weight", an exception occurred :

        Traceback (most recent call last):
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/nn/module.py", line 788, in _load_from_state_dict
            param.copy_(input_param)
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 341, in _copy
            _copy_from_numpy_to_eager_local_tensor(self, other)
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 290, in _copy_from_numpy_to_eager_local_tensor
            assert np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype(
        AssertionError
.
        While copying the parameter "conv_out.bias", an exception occurred :

        Traceback (most recent call last):
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/nn/module.py", line 788, in _load_from_state_dict
            param.copy_(input_param)
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 341, in _copy
            _copy_from_numpy_to_eager_local_tensor(self, other)
          File "/root/anaconda3/envs/oneflow/lib/python3.10/site-packages/oneflow/framework/tensor.py", line 290, in _copy_from_numpy_to_eager_local_tensor
            assert np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype(
        AssertionError`

**Comment by jackalcooper** [comment]
@Yanting-K @ltm920716 are you guys getting the same error when running `convert_original_stable_diffusion_to_diffusers.py` ?

**Comment by Yanting-K** [comment]
yes, the same error!!!

**Comment by zyx1213271098** [comment]
how can i use cache model?
this code run error
`pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    '~/.cache/huggingface/diffusers/models--runwayml--stable-diffusion-v1-5',
    revision="fp16",
    torch_dtype=torch.float16
)`

OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ~/.cache/huggingface/diffusers/models--runwayml--stable-diffusion-v1-5 is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by zyx1213271098** [comment]
Has anyone solved this problem?

**Comment by jackalcooper** [comment]
please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion
