### ISSUE TITLE
oneflow.utils.hooks is not implemented

### ISSUE THREAD

**Issue by terrancewang** [Oneflow-Inc/diffusers#90]
### Describe the bug

installed like this,

git clone https://github.com/Oneflow-Inc/diffusers.git
cd diffusers
python3 -m pip install -e .[oneflow]

### Logs

```shell
Traceback (most recent call last):
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/home/terrance/.local/lib/python3.10/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/terrance/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 27, in <module>
    import torch.utils.hooks as hooks
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "/home/terrance/.local/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py", line 88, in create_module
    raise NotImplementedError(oneflow_mod_fullname + error_msg)
NotImplementedError: oneflow.utils.hooks is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terrance/oneflow/test_diffusion.py", line 2, in <module>
    from diffusers import OneFlowStableDiffusionPipeline
  File "/home/terrance/oneflow/diffusers/src/diffusers/__init__.py", line 22, in <module>
    from transformers import CLIPTextModel, CLIPFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
oneflow.utils.hooks is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.
```

### System Info

cuda 10.2

**Comment by strint** [comment]
@BBuf @daquexian  A op compatibility problem?

**Comment by BBuf** [comment]
> @BBuf @daquexian A op compatibility problem?

The same question here: https://github.com/Oneflow-Inc/OneCloud/issues/185#issuecomment-1333062092 ? It seems that @hhhfccz  have solved it in https://github.com/Oneflow-Inc/oneflow/pull/9837 ?

**Comment by terrancewang** [comment]
Oh OK, I'll try it out later, hopefully it works! Will the PR be merged soon?

**Comment by BBuf** [comment]
> Oh OK, I'll try it out later, hopefully it works! Will the PR be merged soon?

Yes, it will be merged after review done and ci passed.

**Comment by daquexian** [comment]
You can also uninstall accelerator by `pip uninstall accelerator` to solve the error for now.

**Comment by yuikns** [comment]
> You can also uninstall accelerator by `pip uninstall accelerator` to solve the error for now.

Thank you. it works for me as well.

actually the package name should be `accelerate` i guess.

ref: https://pypi.org/project/accelerate/

**Comment by jackalcooper** [comment]
please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion
