### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'mock_torch'

### ISSUE THREAD

**Issue by yuikns** [Oneflow-Inc/diffusers#99]
### Describe the bug

This question is similar to #87, but it seems like I'm not facing the same root error. I had followed @daquexian's solution to install the diffusers using `pip install` instead of `pip install -e` but not works.

Besides, I can reproduce the issue using a py script instead of IPython or other similar notebooks.

According to the `Reproduction` part, it seems like the error may comes from the pollution of `mock_torch.enable` ?

Any advice is super appreciated.

### Reproduction

```py
import oneflow as torch
import torch as og_torch
from diffusers import (
    OneFlowStableDiffusionPipeline as StableDiffusionPipeline,
    OneFlowEulerDiscreteScheduler as EulerDiscreteScheduler,
    OneFlowDPMSolverMultistepScheduler as DPMSolverMultistepScheduler
)
MODEL_ID = "/path/to/a/local/checkpoint"
scheduler = EulerDiscreteScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")
# scheduler = DPMSolverMultistepScheduler.from_config(MODEL_ID, subfolder="scheduler") # also reproducible
diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16) # passing og_torch.float16 also reproducible
```

I pasted the above code to a py script named as `test_loader.py`.

Firstly, let me add some print code in `diffusers/pipeline_oneflow_utils.py` around `torch.mock_torch.enable`

```py
print(f"BEFORE: type: {torch} library_name {library_name} pid {os.getpid()} ppid {os.getppid()}")
traceback.print_stack()
with torch.mock_torch.enable():
    print(f"IN: type: {torch} library_name {library_name} pid {os.getpid()} ppid {os.getppid()}")
    # else we just import it from the library.
    library = importlib.import_module(library_name)

    class_obj = getattr(library, class_name)
```

This is the output

```
BEFORE: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f620662d220>)> library_name transformers pid 3134 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
IN: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f620662d220>)> library_name transformers pid 3134 ppid 95
BEFORE: type: <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'> library_name diffusers pid 3134 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
Traceback (most recent call last):
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 720, in from_pretrained
    with torch.mock_torch.enable():
AttributeError: module 'torch' has no attribute 'mock_torch'
```

And then I imported oneflow as oneflow (😯)

Here is my new header:

```py
...
import numpy as np
import oneflow as torch
import torch as og_torch
import oneflow as oneflow
import traceback

import diffusers
```

And then, I modified `mock_torch.enable()` function as follow:

```py
print(f"BEFORE: type: {torch} library_name {library_name} pid {os.getpid()} ppid {os.getppid()}")
traceback.print_stack()
# with torch.mock_torch.enable():
with oneflow.mock_torch.enable():
    print(f"IN: type: {torch} library_name {library_name} pid {os.getpid()} ppid {os.getppid()}")
    # else we just import it from the library.
    library = importlib.import_module(library_name)

    class_obj = getattr(library, class_name)
```

And I executed the test script again, it finally works

```
BEFORE: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f63c677c1c0>)> library_name diffusers pid 3204 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
IN: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f63c677c1c0>)> library_name diffusers pid 3204 ppid 95
BEFORE: type: <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'> library_name transformers pid 3204 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
IN: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f63c677c1c0>)> library_name transformers pid 3204 ppid 95
BEFORE: type: <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'> library_name transformers pid 3204 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
IN: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f63c677c1c0>)> library_name transformers pid 3204 ppid 95
BEFORE: type: <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'> library_name diffusers pid 3204 ppid 95
  File "test_loader.py", line 10, in <module>
    diffusion_t2m = StableDiffusionPipeline.from_pretrained(MODEL_ID, scheduler=scheduler, revision="fp16", torch_dtype=torch.float16)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/pipeline_oneflow_utils.py", line 719, in from_pretrained
    traceback.print_stack()
IN: type: <module 'torch' (<oneflow.mock_torch.OneflowImporter object at 0x7f63c677c1c0>)> library_name diffusers pid 3204 ppid 95
The config attributes {'class_embed_type': None, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'resnet_time_scale_shift': 'default', 'upcast_attention': False} were passed to OneFlowUNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
```

### System Info

- `diffusers` version: 0.10.0.dev0 ( commit sha `ea94536539aa1f17511b83a85fa08e3b9f989411` )
- Platform: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.12
- PyTorch version (GPU?): 1.12.0+cu116 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 4.26.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: all tried

```
root@f1be73ed83cb:/tmp# pip freeze | grep -E 'oneflow|torch'
oneflow==0.9.0
onnx @ file:///opt/pytorch/pytorch/third_party/onnx
pytorch-quantization==2.1.2
torch==1.12.0+cu116
torch-tensorrt @ file:///opt/pytorch/torch_tensorrt/py/dist/torch_tensorrt-1.1.0a0-cp38-cp38-linux_x86_64.whl
torchaudio==0.12.0+cu116
torchtext==0.13.0
torchvision==0.13.0+cu116
root@f1be73ed83cb:/tmp# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0
```

**Comment by strint** [comment]
@daquexian @jackalcooper

**Comment by jackalcooper** [comment]
please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion
